### ISSUE TITLE
Keyboard flickers on right eye

### ISSUE THREAD

**Issue by Beyley** [galister/wlx-overlay-s#331]
## Description

The keyboard, when I trigger animations (hover over buttons with a cursor) will cause it to flicker in only my right eye. Given I can see tiling in the corruption on some frames (where it only disappears on *some* blocks of rendered pixels), this is 100% some kind of UB with Vulkan and triggering a GPU-side race condition, whether it be a Monado or wlx-overlay-s bug. Unfortunately neither the normal validation layers nor the sync validation layers (+ normal validation with sync stuff enabled) catch anything wrong, which implies it's some missing sync point between wlx-overlay-s rendering, and Monado compositing.

## System Info
**Linux Distribution**: Arch LInux

**Desktop Environment**: Niri 25.08.r47.ge837e39-1

**Kernel version**: 6.18.1-zen1-2-zen-dsc (stock Zen + DSC patches)

**VR Runtime**:
- [x] Monado/WiVRn
- [?] SteamVR/ALVR

**GPU models and driver versions**: 
```
GPU0:
	apiVersion         = 1.4.318
	driverVersion      = 25.2.7
	vendorID           = 0x1002
	deviceID           = 0x73bf
	deviceType         = PHYSICAL_DEVICE_TYPE_DISCRETE_GPU
	deviceName         = AMD Radeon RX 6900 XT (RADV NAVI21)
	driverID           = DRIVER_ID_MESA_RADV
	driverName         = radv
	driverInfo         = Mesa 25.2.7-arch1.1
	conformanceVersion = 1.4.0.0
	deviceUUID         = 00000000-0300-0000-0000-000000000000
	driverUUID         = 414d442d-4d45-5341-2d44-525600000000
GPU1:
	apiVersion         = 1.4.318
	driverVersion      = 25.2.7
	vendorID           = 0x8086
	deviceID           = 0x4680
	deviceType         = PHYSICAL_DEVICE_TYPE_INTEGRATED_GPU
	deviceName         = Intel(R) UHD Graphics 770 (ADL-S GT1)
	driverID           = DRIVER_ID_INTEL_OPEN_SOURCE_MESA
	driverName         = Intel open-source Mesa driver
	driverInfo         = Mesa 25.2.7-arch1.1
	conformanceVersion = 1.4.0.0
	deviceUUID         = 86808046-0c00-0000-0002-000000000000
	driverUUID         = 5d4dd73d-77e4-9ab8-98bb-a7b72f326797
```

## Overlay Logs

(nothing from validation layers)

[wlx.log](https://github.com/user-attachments/files/24343124/wlx.log)

**Comment by galister** [comment]
Overlays in general (except screens set to SBS stereo) are only rendered once per frame and then submitted as a single layer with `XR_EYE_VISIBILITY_BOTH`.

The rendering tasks are submitted to the GPU after xrAcquireSwapchainImage, [here](https://github.com/galister/wlx-overlay-s/blob/86cbe8f13bf49a3137318bd911dd3d1c466a5ae9/wlx-overlay-s/src/backend/openxr/mod.rs#L412-L416)

All GPU futures are then joined together, [signaling a fence when done](https://github.com/galister/wlx-overlay-s/blob/86cbe8f13bf49a3137318bd911dd3d1c466a5ae9/wlx-overlay-s/src/graphics/mod.rs#L672-L685). The fence is then [awaited](https://github.com/galister/wlx-overlay-s/blob/86cbe8f13bf49a3137318bd911dd3d1c466a5ae9/wlx-overlay-s/src/backend/openxr/mod.rs#L427) before we call xrEndFrame.


You might want to try with a different version of Monado.

Could also try with the [next-dash-interface](https://github.com/galister/wlx-overlay-s/tree/next-dash-interface) branch, where we got rid of EGL completely. EGL has a history of causing issues, such as image corruption. However, those issues were seemingly limited to apps running under WayVR.

**Comment by galister** [comment]
Are you getting this on the latest release, too? I haven't seen anyone else report this.

**Comment by DeltaNeverUsed** [comment]
I am also experiencing this, I was on the old version too (wlx-overlay-s)
Also using Monado, last compiled from main brain on 23-01-2026

**Comment by galister** [comment]
Just to confirm, you are both on vanilla Monado? Not WiVRn etc?

**Comment by DeltaNeverUsed** [comment]
Yes, vanilla monado, using XRizer, it seems to only really happen during the loading screen in vrchat

**Comment by galister** [comment]
I have not seen it with WiVRn, though WiVRn uses a custom compositor over Monado's. It might be that the bug is in the vanilla Monado compositor. It might be worth opening a ticket with them.

**Comment by MattiRegenhardt** [comment]
I can now report the same issue on WiVRn. The last known good run was on Sunday, so running the current version ( 4fc439a) and the only other relevant component being WiVRn flatpak, which did have an update. Running Hyprland 0.53.3 on archlinux 6.18.9-zen1-2-zen.

**Comment by galister** [comment]
Care to make a video recording using the headset's screen recorder?

**Comment by MattiRegenhardt** [comment]
Will do as soon as I'm back home on the weekend. Also another note I forgot to mention in my previous comment: this seems to be an issue with general overlay rendering. Displays are affected by the same flicker but much much less frequent.

**Comment by MattiRegenhardt** [comment]
Good and bad news. I can't seem to reproduce this anymore.

**Comment by galister** [comment]
where was a vulkan bug in wivrn that got fixed in yesterday's release

**Comment by Beyley** [comment]
I'm still getting this on latest Monado (stock upstream) and WayVR, although annoyingly I only get it when I'm *not* in the mood to do debugging or to drop everything I'm doing to capture footage of it. It also effects more than just the keyboard, *any* active rendering done with the GUI backend bugs out (only when the GUI re-renders does it bug out), so the edit mode UI especially is very very effected since there's lots of animations.

**Comment by galister** [comment]
did this ever get better for you?

**Comment by DeltaNeverUsed** [comment]
I haven't seen this happen in a long while now
